name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main  # hoặc branch bạn code chính

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install
        run: |
          rm -f package-lock.json
          rm -rf node_modules
          npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
          force_orphan: true